name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_terraform:
    runs-on: hashicorp/terraform:1.8
    steps:
      - name: Rewrites all Terraform configuration files to a canonical format
        run: terraform fmt -diff -check -recursive

  generate_docs:
    runs-on: quay.io/terraform-docs/terraform-docs:v0.17.0
    steps:
      - name: Generate documentation from Terraform modules
        run: |
          terraform-docs --version
          ./scripts/generate_docs.sh

  check_docs:
    runs-on: alpine/git:2.45.1
    steps:
      - name: Check if the documents have been updated
        run: |
          git diff
          git status --porcelain --untracked-files=all
          if [ -n "$(git status --porcelain --untracked-files=no)" ]; then echo "Error changes detected ${CHANGES}"; exit 1; fi

  run_sanity_checks:
    runs-on: hashicorp/terraform:1.8
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
      AWS_DEFAULT_REGION: us-east-1
      BASE64_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.BASE64_GOOGLE_APPLICATION_CREDENTIALS }}
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT_ID }}
    steps:
      - name: Test the Terraform code inside the ./tests folder to make sure the modules/recipes are working
        run: |
          echo $BASE64_GOOGLE_APPLICATION_CREDENTIALS | base64 -d > ./gcp-ci_sa.json
          export GOOGLE_APPLICATION_CREDENTIALS="./gcp-ci_sa.json"
          ./scripts/run_sanity_checks.sh tests
